### ISSUE TITLE
Support for Sony MZ-RH1 & RH10

### ISSUE THREAD

**Issue by DaveFlashNL** [enimatek-nl/go-netmd-cli#4]
Hi there I have the Sony MZ-RH1 & RH10,

can you add support for those units?

much thanks.

**Comment by enimatek-nl** [comment]
RH1 and RH10 are listed already (see https://github.com/enimatek-nl/go-netmd-lib/blob/20fc1fffea77a9421bb595aa1c651b303eb719b5/device.go#L47)
But since those units are HiMD you can only use them in 'NetMD' mode (with normal (LP/SP) formatted MD's that is).

HiMD support is out of the scope of go-netmd-lib.
